### ISSUE TITLE
campilation error

### ISSUE THREAD

**Issue by matuzyaka** [dsuarezv/GearSolver#1]
good afternoon. I want to make the hypocycloidal reducer for my kayak and ran into a problem. compile errors appear. Unfortunately I am not a programmer and I can not cope with it. You can not share the compiled exe file?
my email matus@ukr.net
thank you

**Comment by dsuarezv** [comment]
Hi,

Here is a compiled version:

https://drive.google.com/file/d/0BxWgsl4MRfSgbmxZeHZjSE9PY2s/view?usp=sharing

Best!

David

**Comment by matuzyaka** [comment]
thank you very much! you are the best! if you will visit Zaporozhye, youll have beer, river and my kayaks)))) 
this is my FB https://www.facebook.com/dar.veter.1 
thank you! 
05 марта 2017, 10:06:26, от David Suarez < notifications@github.com >: 
Hi, 

Here is a compiled version: 

https://drive.google.com/file/d/0BxWgsl4MRfSgbmxZeHZjSE9PY2s/view?usp=sharing 

Best! 

David

**Comment by dsuarezv** [comment]
Hehe, thanks! I would love to see some pictures of the gears when you build
them, if you want to share them.

Cheers!

David

**Comment by matuzyaka** [comment]
ок) 

05 марта 2017, 10:22:39, от David Suarez < notifications@github.com >: 
Hehe, thanks! I would love to see some pictures of the gears when you build 
them, if you want to share them. 

Cheers! 

David

**Comment by matuzyaka** [comment]
hello David. I'm sorry to trouble you. i make one cycloidal gear what i need in your programm, and have result .dxf (in attachment).  
open it in solidworks. internal faces of cycloid disk i think incorrect. I will correct it in SW, but think this info will help u. 
05 марта 2017, 10:22:39, от David Suarez < notifications@github.com >: 

Hehe, thanks! I would love to see some pictures of the gears when you build 
them, if you want to share them. 

Cheers! 

David

**Comment by dsuarezv** [comment]
Hey, can't see the attachment, can you send it using the issues page in github?

**Comment by dsuarezv** [comment]
Precompiled binaries are now available in the repo in the /Binaries folder. Will close this.
