### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matuzyaka** [dsuarezv/GearSolver#2]
i make one cycloidal gear what i need in your programm, and have result .dxf (in attachment). 
open it in solidworks. internal faces of cycloid disk i think incorrect.
![screenshot_7](https://cloud.githubusercontent.com/assets/26138072/23693799/fcdc87d8-03de-11e7-88ff-b8694fefce16.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/26138072/23693800/fcde914a-03de-11e7-95d0-8f8d80b468e6.png)

**Comment by dsuarezv** [comment]
Try generating the gear selecting the option "Cycloid gear" in the top combobox. 

I recall having issues with the import in SolidWorks with the Sensinger method.

**Comment by dsuarezv** [comment]
Long time no answer, will close for now.
